version: '3'

networks:
  dev_proxy_network:

services:
  webserver:
    working_dir: /usr/src/app
    image: maxeo90/web-dev:node-js-base
    # docker pull maxeo90/web-dev:node-js-base
    #build:
    #  context: ./
    #  dockerfile: dockerconfig/webserver/Dockerfile
    volumes:
      - ./app:/usr/src/app
      - ./dockerconfig/webserver/docker-run:/docker-run
    environment:
      - 'TZ=Europe/Rome'
    networks:
      - dev_proxy_network


  reverse_proxy:
    image: maxeo90/reverse-proxy
    #docker pull maxeo90/reverse-proxy
    #build:
    #  context: ./
    #  dockerfile: dockerconfig/reverse_proxy/Dockerfile
    volumes:
      - ./dockerconfig/reverse_proxy/cert/docker:/dockerconfig/cert
      - ./dockerconfig/reverse_proxy/cert/letsencrypt:/etc/letsencrypt
      - ./dockerconfig/reverse_proxy/apache/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./dockerconfig/reverse_proxy/docker-run:/docker-run
    environment:
      RP_PORT_FROM: '${RP_PORT_FROM}'
      RP_PORT_FROM_SSL: '${RP_PORT_FROM_SSL}'
      TZ: '${TZ}'
    networks:
      - dev_proxy_network
    ports:
      - "${RP_PORT_FROM}:80"
      - "${RP_PORT_FROM_SSL}:443"
